### PR TITLE
Fixes #13603 - emit error message guiding users to repo and CV export

### PR DESCRIPTION
**Pull request by beav**
katello-disconnected has been replaced by repo and CV export functionality.
This commit updates the `katello-disconnected` script to tell users to use the
new functionality.

See http://www.katello.org/docs//user_guide/disconnected/ for additional detail.

### CODE REVIEW

**Comment by sean797** [comment]
I'm not sure we should be breaking people installs and requiring them to upgrade on the spot? If you want to do it that way we should probably remind them they can downgrade for the time being using `yum downgrade katello-utils` or we could print an error message telling them to upgrade on every command they run.

**Comment by ehelms** [comment]
@sean797 the alternative is that this includes a warning message every time they try to use it. There is no guarantee this even still works in its current form against 3.0 and we don't plan to support it ourselves. I am OK leaving the code in tact with the message though if that will alleviate some pain in transition.

**Comment by sean797** [comment]
@ehelms if there's no guarantee it will work against 3.0 it may be better to just display the error message rather than releasing a version that were not sure it going to work. I'm happy with whatever you decide :+1:

**Comment by beav** [comment]
@sean797 @ehelms I am :+1: for this PR in its current form since it's for 3.0. If it was 2.4 or something I would recommend adding the message with a deprecation warning.

**Comment by ehelms** [comment]
Thanks @beav !

**Pull request merged**
